name: bsl_support
description: "A new Flutter project."
publish_to: "none"
version: 1.0.2+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  json_annotation: ^4.9.0
  
  go_router: ^14.6.1

  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  equatable: ^2.0.7
  
  video_player: ^2.9.2
  chewie: ^1.8.5
  
  intl: ^0.19.0
  envied: ^1.0.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  envied_generator: ^1.0.0
  custom_lint: ^0.7.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - assets/tvs/
